name: Pull Request Work Flow
on: 
  pull_request:
    types:
     - opened
     - closed
     - edited
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "how are you today Mr. Robot?"